services:
  - type: web
    name: task-manager-api
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg-learning-python
          property: connectionString
    plan: free

databases:
  - name: pg-learning-python
    plan: free